"""add baseline to anomaly

Revision ID: d50429135a98
Revises: 179da1cd69ff
Create Date: 2025-12-27 07:37:14.847837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50429135a98'
down_revision: Union[str, None] = '179da1cd69ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomaly_results', sa.Column('baseline', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anomaly_results', 'baseline')
    # ### end Alembic commands ###
